import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "ClubZen",
  description: "Generated by create next app",
};

import "./globals.css";
// shadcn imports

import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

// component import
import Navbar from "@/components/nav/Navbar";

// font import
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar></Navbar>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
